/**
 * CBA × H2O.ai Engagement — Master Data Store
 * Single source of truth for all website pages.
 * Last updated: June 2026
 */

const CBA_DATA = {

  // ── PARTNERSHIP OVERVIEW ─────────────────────────────────────────────────
  partnership: {
    client: "Commonwealth Bank of Australia",
    vendor: "H2O.ai",
    tier: "Tier 0",
    status: "SOW Execution",
    commitment: 100,          // $M AUD, 3-year
    mapped_tcv: 34,           // $M AUD across all scoped UCs
    committed_tcv: 25,        // $M AUD in active/near-signed SOWs
    existing_platform: 7.9,   // $M AUD platform commitment (Dec 2026)
    fy: "FY27",
    period: "July 2026 – June 2027",
    license_pct: 80,
    services_pct: 20,
    account_exec: "Yohan Trevoy",
    engagement_lead: "Shivam Bansal",
  },

  // ── SIZING REFERENCE ────────────────────────────────────────────────────
  sizing: {
    "M":     { label: "Medium",    duration: "6 months",      tcv: 1,  color: "#22c55e" },
    "L":     { label: "Large",     duration: "6–9 months",    tcv: 2,  color: "#3b82f6" },
    "L SLM": { label: "Large SLM", duration: "up to 9 months",tcv: 1,  color: "#8b5cf6" },
    "XL":    { label: "Extra Large",duration: "up to 9 months",tcv: 3, color: "#f59e0b" },
    "XXL":   { label: "XXL",       duration: "up to 12 months",tcv: 5, color: "#ef4444" },
  },

  // ── USE CASES (master) ─────────────────────────────────────────────────
  usecases: [
    {
      id: 1,
      name: "SLM Factory — Core Capability Build",
      shortName: "SLM Factory",
      bu: "CDAO AI Platform",
      category: "SLM Factory",
      sizing: "XXL",
      duration: "up to 12 months",
      tcv: 5,   tcv_license: 4,   tcv_services: 1,
      status: "green",
      statusLabel: "In Progress",
      readiness: "Dependency on Platform",
      dependency: "HAIC 26.04.0 Release",
      roi: "$20M",
      priority: 1,
      products: ["H2O AI Factory", "Enterprise LLM Studio", "Model Zoo", "Label Factory", "Tuning/Distillation Engine", "Data Generation Agent"],
      stakeholders_cba: ["David Rowe", "Tyrone Pollard", "Andrea Nicastro", "Jan Gluschke", "Blair Hudson"],
      h2o_lead: "Eu Jin (KGM)",
      h2o_team: ["Eu Jin (KGM)", "Piraveen", "Sunny", "Branden Murray", "Pascal & team"],
      sow_link: "https://docs.google.com/document/d/1EhKE8v-fmsJlWRyOmejpsMcXUQQu1FA6/edit",
      description: "Scale CBA's banking-SLM portfolio from 4 guardrail SLMs in production today to 10+ and bring down frontier-model consumption costs.",
      components: ["A. Labelling Factory", "B. Synthetic Data Generator", "C. Distillation & Fine Tuning Engine", "D. Model Zoo (Inferencing)", "E. Coding Harness / Agentic Assistant"],
      next_step: "Complete Alignment on SOW | followed by CBA Stakeholder discussion",
      phase: "Build",
      build_cost: 5000000,
      maintenance_cost: 1000000,
      usage_cost_qtr: 500000,
    },
    {
      id: 2,
      name: "BB SLM — Compliance Detection",
      shortName: "BB Compliance SLM",
      bu: "Business Banking",
      category: "SLM Build",
      sizing: "L SLM",
      duration: "up to 9 months",
      tcv: 1,   tcv_license: 0.6,  tcv_services: 0.4,
      status: "green",
      statusLabel: "In Progress",
      readiness: "Dependency on Platform",
      dependency: "HAIC 26.04.0 Release",
      roi: null,
      priority: 1,
      products: ["H2O Enterprise LLM Studio", "Document AI/OCR Engine"],
      stakeholders_cba: ["Sonal Surana", "Abdul Karim"],
      h2o_lead: "Piraveen",
      h2o_team: ["Piraveen", "Sunny"],
      sow_link: "https://docs.google.com/document/d/1NWagu44mxy06yUVd8iAjkqONXKzQLe6O/edit",
      description: "Implement explainable SLM-based compliance monitoring to perform high-volume conversational guardrail checks efficiently, reducing latency, cost, and manual review effort.",
      components: ["A. Discovery", "B. Build", "C. Deployment Artifacts"],
      next_step: "Complete Alignment on SOW | internal review then resend",
      phase: "Build",
      build_cost: 2000000,
      maintenance_cost: 400000,
      usage_cost_qtr: 200000,
    },
    {
      id: 3,
      name: "BB SLM — Document Classification",
      shortName: "BB Doc Classification",
      bu: "Business Banking",
      category: "SLM Build",
      sizing: "L SLM",
      duration: "up to 9 months",
      tcv: 1,   tcv_license: 0.6,  tcv_services: 0.4,
      status: "green",
      statusLabel: "In Progress",
      readiness: "Dependency on Platform",
      dependency: "HAIC 26.04.0 Release",
      roi: null,
      priority: 1,
      products: ["H2O Enterprise LLM Studio", "Document AI/OCR Engine"],
      stakeholders_cba: ["Sonal Surana", "Abdul Karim"],
      h2o_lead: "TBH - 1 (Syd)",
      h2o_team: ["TBH - 1 (Syd)", "TBH - 2 (Syd)", "TBH - 3 (Syd)"],
      sow_link: "https://docs.google.com/document/d/1Z5Gb71S2xE_-KQIu_Rccep5e2hGxYW9h/edit",
      description: "Implement multimodal SLM-based document classification for lending documents to improve processing speed, reduce LLM inference costs, and enable scalable production-ready classification.",
      components: [],
      next_step: "Complete Alignment on SOW | internal review then resend",
      phase: "Build",
      build_cost: 2000000,
      maintenance_cost: 400000,
      usage_cost_qtr: 200000,
    },
    {
      id: 4,
      name: "RBS SLM — Financial Companion (Tools)",
      shortName: "RBS Financial Companion",
      bu: "Retail Banking Services",
      category: "SLM Build",
      sizing: "L SLM",
      duration: "up to 9 months",
      tcv: 1,   tcv_license: 0.6,  tcv_services: 0.4,
      status: "green",
      statusLabel: "In Progress",
      readiness: "Dependency on Platform",
      dependency: "HAIC 26.04.0 Release",
      roi: null,
      priority: 1,
      products: ["H2O ELLM Studio", "Hydrogen Torch", "H2O MLOps"],
      stakeholders_cba: ["Michael Bauman", "Boris Kogan"],
      h2o_lead: "Sunny",
      h2o_team: ["Sunny"],
      sow_link: "https://docs.google.com/document/d/1c2TkbNluFEb3EhCmEeNwG_gsIFnO4vo2/edit",
      description: "Optimise customer-facing conversational AI by reducing inference costs and latency through model fine-tuning, task-specific model orchestration, and efficient deployment architectures.",
      components: [],
      next_step: "Complete Alignment on SOW | requirements clarity deep dive",
      phase: "Build",
      build_cost: 1000000,
      maintenance_cost: 200000,
      usage_cost_qtr: 100000,
    },
    {
      id: 5,
      name: "Financial Companion — Compliance SLM",
      shortName: "FC Compliance SLM",
      bu: "Retail Banking Services",
      category: "SLM Build",
      sizing: "L SLM",
      duration: "up to 9 months",
      tcv: 1,   tcv_license: 0.6,  tcv_services: 0.4,
      status: "green",
      statusLabel: "In Progress",
      readiness: "Dependency on Platform",
      dependency: "HAIC 26.04.0 Release",
      roi: null,
      priority: 1,
      products: ["H2O Enterprise LLM Studio"],
      stakeholders_cba: ["Boris Kogan"],
      h2o_lead: "Sunny",
      h2o_team: ["Sunny", "TBH - 10 (Syd)"],
      sow_link: null,
      description: "Replace the existing LLM-driven compliance pipeline with a hybrid system, using fine-tuned SLMs for standardisable safety checks and reserving the frontier LLM only for genuinely complex reasoning.",
      components: [],
      next_step: "Complete Alignment on SOW | deep dive next week then align and sign",
      phase: "Scoping",
      build_cost: 1000000,
      maintenance_cost: 200000,
      usage_cost_qtr: 100000,
    },
    {
      id: 6,
      name: "Group Audit & Assurance — Complaints SLM",
      shortName: "GAA Complaints SLM",
      bu: "Group Audit & Assurance",
      category: "SLM Build",
      sizing: "L SLM",
      duration: "up to 9 months",
      tcv: 1,   tcv_license: 0.6,  tcv_services: 0.4,
      status: "green",
      statusLabel: "In Progress",
      readiness: "Dependency on Platform",
      dependency: "HAIC 26.04.0 Release",
      roi: null,
      priority: 1,
      products: ["H2O Enterprise LLM Studio"],
      stakeholders_cba: [],
      h2o_lead: "TBH - 2 (Syd)",
      h2o_team: ["TBH - 2 (Syd)", "TBH - 4 (Syd)", "Sunny"],
      sow_link: "https://docs.google.com/document/d/1s46wbx5FfBivXx5USwxN8f88Nwu2-g3T/edit",
      description: "Replace the existing LLM-based complaints-detection pipeline with a hybrid system, using fine-tuned SLMs for high-confidence classifications and reserving the frontier LLM only for ambiguous cases.",
      components: [],
      next_step: "SOW target submission Monday",
      phase: "Scoping",
      build_cost: 1000000,
      maintenance_cost: 200000,
      usage_cost_qtr: 100000,
    },
    {
      id: 7,
      name: "IB&M — Predictive Hedging Foundation Model",
      shortName: "IB&M Predictive Hedging",
      bu: "Institutional Banking & Markets",
      category: "Tabular / Predictive",
      sizing: "XL",
      duration: "up to 12 months",
      tcv: 3,   tcv_license: 2.4,  tcv_services: 0.6,
      status: "green",
      statusLabel: "In Progress",
      readiness: "Dependency on Platform",
      dependency: "HAIC 26.04.0 Release",
      roi: "$100M",
      priority: 1,
      products: ["TabH2O-F / timeH2O", "Data Preparation Templates", "H2O AI Cloud"],
      stakeholders_cba: ["Andrea Schmidt", "Prakash Mallick", "Keith Wong"],
      h2o_lead: "Eu Jin (KGM)",
      h2o_team: ["Eu Jin (KGM)", "Piraveen", "TBH - 8 (Syd)", "Mark Landry", "Pascal & team"],
      sow_link: "https://docs.google.com/document/d/1qk2qTBY6yef9-Y-QlSBrhidv7Y3ICwx3/edit",
      description: "Build a proprietary TabH2O-F foundation model trained on CBA's 10TB market data and integrated into the existing ensemble. Execute final fine-tuning within CBA's environment.",
      components: [],
      next_step: "In-person session with IB&M team | clarify data sources and integration",
      phase: "Build",
      build_cost: 3000000,
      maintenance_cost: 600000,
      usage_cost_qtr: 300000,
    },
    {
      id: 8,
      name: "BB — Predictive Models Uplift",
      shortName: "BB Predictive Models",
      bu: "Business Banking",
      category: "Predictive",
      sizing: "XL",
      duration: "up to 9 months",
      tcv: 3,   tcv_license: 2.4,  tcv_services: 0.6,
      status: "green",
      statusLabel: "Can Start — Discovery",
      readiness: "Can Start — Discovery",
      dependency: null,
      roi: "$30M",
      priority: 1,
      products: ["AutoResearch for ML/DS Agent", "TabH2O", "H2O AutoML", "Driverless AI", "MLOps"],
      stakeholders_cba: ["Sonal Surana", "Stephan Hanks"],
      h2o_lead: "Ishan",
      h2o_team: ["Ishan", "Rohit (KGM)", "TBH - 11 (Ind)"],
      sow_link: "https://docs.google.com/document/d/1nzGlgRkKf_DswqW7a6hYehunbRyZS5G_/edit",
      description: "Uplift Business Banking's ~15 propensity and Next-Best-Action models which drive RM-led campaigns across BBL, business loan cross-sell, and retention.",
      components: [],
      next_step: "Internal prep call with Shivam before CBA session",
      phase: "Discovery",
      build_cost: 3000000,
      maintenance_cost: null,
      usage_cost_qtr: null,
    },
    {
      id: 9,
      name: "Home Buying & Loan Insurance Cross-Selling",
      shortName: "Home Buying / Insurance",
      bu: "Home Buying",
      category: "Predictive",
      sizing: "L",
      duration: "up to 9 months",
      tcv: 2,   tcv_license: 1.6,  tcv_services: 0.4,
      status: "green",
      statusLabel: "Can Start — Discovery",
      readiness: "Can Start — Discovery",
      dependency: null,
      roi: "$50M",
      priority: 1,
      products: ["AutoResearch for ML/DS Agent", "TabH2O", "Driverless AI", "MLOps"],
      stakeholders_cba: ["Andy", "Suzelle Nunes"],
      h2o_lead: "Rohit (KGM)",
      h2o_team: ["Rohit (KGM)", "TBH - 11 (Ind)", "TBH - 12 (Syd/SL/Ind)"],
      sow_link: "https://docs.google.com/document/d/1a0RyYyAcOWS6BKXugTfdsD7PSR13XlWd/edit",
      description: "Lift home insurance attachment from 25.8% to 30%; focus on back-book diagnostics, cohort segmentation and test interventions.",
      components: [],
      next_step: "Complete Alignment on SOW | finalise after CBA procurement pass",
      phase: "Scoping",
      build_cost: 2000000,
      maintenance_cost: null,
      usage_cost_qtr: null,
    },
    {
      id: 10,
      name: "FS — Balance Sheet Forecasting",
      shortName: "FS Forecasting",
      bu: "Financial Services",
      category: "Tabular / Predictive",
      sizing: "L",
      duration: "up to 9 months",
      tcv: 2,   tcv_license: 1.6,  tcv_services: 0.4,
      status: "green",
      statusLabel: "Can Start — Discovery",
      readiness: "Can Start — Discovery",
      dependency: null,
      roi: "$30M",
      priority: 1,
      products: ["AutoResearch for ML/DS Agent", "TabH2O", "Driverless AI", "MLOps"],
      stakeholders_cba: ["Oliver Fleming", "Gavin W Marsh", "Liam Pattison"],
      h2o_lead: "Phil",
      h2o_team: ["Phil", "Tristan", "Sean"],
      sow_link: "https://docs.google.com/document/d/1XwqrqNahh3Yqgr3WYOBBTrpcEWefGRQE/edit",
      description: "Modernise Treasury forecasting by replacing backwards-looking, ETL-constrained processes with AI-driven predictive forecasting to improve balance sheet visibility and optimise hedging decisions.",
      components: [],
      next_step: "Complete Alignment on SOW | include data engineering work without fixed dates",
      phase: "Scoping",
      build_cost: 2000000,
      maintenance_cost: null,
      usage_cost_qtr: null,
    },
    {
      id: 11,
      name: "Transaction Intelligence & Classification (Feature Store)",
      shortName: "Txn Intelligence",
      bu: "CDAO AI Platform",
      category: "Feature Factory",
      sizing: "XXL",
      duration: "up to 12 months",
      tcv: 5,   tcv_license: 4,   tcv_services: 1,
      status: "amber",
      statusLabel: "Discussions Ongoing",
      readiness: "Dependent on Client Discussion",
      dependency: null,
      roi: "$30M",
      priority: 1,
      products: ["Feature Store", "SLM/LLM Studio Enterprise", "TabH2O", "Driverless AI", "MLOps"],
      stakeholders_cba: ["David Rowe", "Tyrone Pollard"],
      h2o_lead: "Phil",
      h2o_team: ["Phil", "Tristan", "Sean", "TBH - 12 (Syd/SL/Ind)"],
      sow_link: "https://docs.google.com/document/d/1h_5_5S-z_vuFnTQf6T374GQ-fD6vpTyk/edit",
      description: "Build consistent transaction data classification across CBA that can be leveraged for a range of use cases, converting classified transaction data into reusable customer signals.",
      components: ["Multi-granularity Feature Asset", "Data Engineering / Source Consolidation", "Governed Feature Catalogue"],
      next_step: "Keep CBA sessions going — Love organising deep dives | align SOW",
      phase: "Active Discovery",
      build_cost: 5000000,
      maintenance_cost: null,
      usage_cost_qtr: null,
    },
    {
      id: 12,
      name: "Scam & Fraud Detection (3 Use Cases)",
      shortName: "Fraud Detection",
      bu: "COO",
      category: "Predictive",
      sizing: "L",
      duration: "up to 6–12 months",
      tcv: 3,   tcv_license: 2.4,  tcv_services: 0.6,
      status: "green",
      statusLabel: "SOW In Progress",
      readiness: "Can Start — Discovery",
      dependency: null,
      roi: null,
      priority: 1,
      products: ["AutoResearch for ML/DS Agent", "TabH2O", "H2O AutoML", "MLOps"],
      stakeholders_cba: [],
      h2o_lead: "Sean",
      h2o_team: ["Sean", "TBH - 5 (Syd)", "TBH - 8 (Syd)"],
      sow_link: "https://docs.google.com/document/d/1JbevxiQG6fAdLDJZHEzGm5JVxknGxJqC/edit",
      description: "Three use cases: (1) Autonomous model training/deployment for fraud/scam detection. (2) Unsupervised detection of emerging F&S behaviour. (3) Fraud modelling infrastructure efficiency review.",
      components: ["12.1 Autonomous Model Training & Deployment", "12.2 Unsupervised Emerging Behaviour Detection", "12.3 Infrastructure Efficiency Review"],
      next_step: "SOW to be completed and sent to CBA next week",
      phase: "SOW Drafting",
      build_cost: 3000000,
      maintenance_cost: null,
      usage_cost_qtr: null,
    },
    {
      id: 13,
      name: "MLOps Revamp",
      shortName: "MLOps Revamp",
      bu: "CDAO AI Platform",
      category: "Strategic",
      sizing: "XL",
      duration: "up to 12 months",
      tcv: 2,   tcv_license: 1.6,  tcv_services: 0.4,
      status: "red",
      statusLabel: "On Hold / TBC",
      readiness: "Dependent on Client Discussion",
      dependency: null,
      roi: "$20M",
      priority: 3,
      products: ["H2O MLOps"],
      stakeholders_cba: ["Leandro Arranz", "Igor Maksaev Brockway", "Ajay Chawla"],
      h2o_lead: "TBH - 1 (Syd)",
      h2o_team: ["-", "-", "-"],
      sow_link: "https://docs.google.com/document/d/19I_n8Pfi1_ezNYqmA9jQI5dGJWcztdfN/edit",
      description: "Assess deployment blockers across data access, model risk, governance and integration; avoid broad platform rebuild.",
      components: [],
      next_step: "TBD — awaiting CBA prioritisation",
      phase: "On Hold",
      build_cost: 2000000,
      maintenance_cost: null,
      usage_cost_qtr: null,
    },
    {
      id: 14,
      name: "RBS — CEM Classification",
      shortName: "CEM Classification",
      bu: "Retail Banking Services",
      category: "Predictive",
      sizing: "L",
      duration: "up to 9 months",
      tcv: 1,   tcv_license: 0.6,  tcv_services: 0.4,
      status: "red",
      statusLabel: "Paused / TBD",
      readiness: "Dependent on Client Discussion",
      dependency: null,
      roi: null,
      priority: 3,
      products: ["h2oGPTe", "Document AI", "MLOps"],
      stakeholders_cba: ["Dean Sandavers"],
      h2o_lead: "-",
      h2o_team: ["-", "-"],
      sow_link: null,
      description: "Uplift the non-commercial message classification model for Digital/CEE. Assess the existing in-house LLM baseline, run fine-tuning and evaluation experiments.",
      components: [],
      next_step: "Tristan to keep reading notes; prepare SOW only if CBA comes back",
      phase: "Paused",
      build_cost: 1000000,
      maintenance_cost: null,
      usage_cost_qtr: null,
    },
    {
      id: 15,
      name: "CDAO — AI Governance & Controls",
      shortName: "AI Governance",
      bu: "CDAO AI Platform",
      category: "Strategic",
      sizing: "XL",
      duration: "up to 9 months",
      tcv: 3,   tcv_license: 2.4,  tcv_services: 0.6,
      status: "amber",
      statusLabel: "Discussions Ongoing",
      readiness: "Dependent on Client Discussion",
      dependency: null,
      roi: null,
      priority: 2,
      products: ["H2O Evals", "MLOps", "h2oGPTe"],
      stakeholders_cba: [],
      h2o_lead: "TBH",
      h2o_team: ["TBH - 5 (Syd)"],
      sow_link: null,
      description: "Guardrails, Evals and MRM framework for CDAO. Discussion to be initiated — discovery sessions started.",
      components: [],
      next_step: "Discovery sessions ongoing",
      phase: "Discovery",
      build_cost: 3000000,
      maintenance_cost: null,
      usage_cost_qtr: null,
    },
  ],

  // ── DELIVERY TIMELINE ──────────────────────────────────────────────────
  // Columns: Jul-26, Aug-26, Sep-26, Oct-26, Nov-26, Dec-26, Jan-27, Feb-27, Mar-27, Apr-27, May-27, Jun-27
  timeline: {
    months: ["Jul '26","Aug '26","Sep '26","Oct '26","Nov '26","Dec '26","Jan '27","Feb '27","Mar '27","Apr '27","May '27","Jun '27"],
    projects: [
      { id:1,  name: "SLM Factory",          phases: [{s:0,e:1,label:"A&D",type:"ad"},{s:1,e:8,label:"Build",type:"build"},{s:8,e:10,label:"Benchmarking",type:"bench"},{s:10,e:12,label:"Handover",type:"handover"}] },
      { id:2,  name: "BB Compliance SLM",    phases: [{s:0,e:0.5,label:"Discovery",type:"ad"},{s:0.5,e:8,label:"Build",type:"build"},{s:8,e:10,label:"Bench",type:"bench"},{s:10,e:11,label:"Handover",type:"handover"},{s:11,e:12,label:"Maint",type:"maint"}] },
      { id:3,  name: "BB Doc Classification",phases: [{s:0,e:0.5,label:"Discovery",type:"ad"},{s:0.5,e:8,label:"Build",type:"build"},{s:8,e:10,label:"Bench",type:"bench"},{s:10,e:11,label:"Handover",type:"handover"},{s:11,e:12,label:"Maint",type:"maint"}] },
      { id:4,  name: "RBS Financial Companion",phases: [{s:0,e:0.5,label:"Data Prep",type:"ad"},{s:0.5,e:6,label:"Build",type:"build"},{s:6,e:8,label:"Bench",type:"bench"},{s:8,e:9,label:"Handover",type:"handover"},{s:9,e:12,label:"Maint",type:"maint"}] },
      { id:5,  name: "FC Compliance SLM",    phases: [{s:0,e:0.5,label:"Data Prep",type:"ad"},{s:0.5,e:8,label:"Build",type:"build"},{s:8,e:10,label:"Bench",type:"bench"},{s:10,e:11,label:"Handover",type:"handover"},{s:11,e:12,label:"Maint",type:"maint"}] },
      { id:6,  name: "GAA Complaints SLM",   phases: [{s:0,e:0.5,label:"Data Struct",type:"ad"},{s:0.5,e:8,label:"Build",type:"build"},{s:8,e:10,label:"Bench",type:"bench"},{s:10,e:11,label:"Handover",type:"handover"},{s:11,e:12,label:"Maint",type:"maint"}] },
      { id:7,  name: "IB&M Hedging FM",      phases: [{s:0,e:1,label:"A&D",type:"ad"},{s:1,e:8,label:"Build",type:"build"},{s:8,e:10,label:"Bench",type:"bench"},{s:10,e:11,label:"Handover",type:"handover"},{s:11,e:12,label:"Maint",type:"maint"}] },
      { id:8,  name: "BB Predictive Models", phases: [{s:0,e:1,label:"A&D",type:"ad"},{s:1,e:5,label:"Build",type:"build"},{s:5,e:6,label:"Bench",type:"bench"},{s:6,e:7,label:"Handover",type:"handover"},{s:7,e:9,label:"Monitoring",type:"maint"},{s:9,e:12,label:"Next Batch",type:"build"}] },
      { id:9,  name: "Home Buying/Insurance", phases: [{s:0,e:1,label:"A&D",type:"ad"},{s:1,e:5,label:"Build",type:"build"},{s:5,e:6,label:"Bench",type:"bench"},{s:6,e:7,label:"Handover",type:"handover"},{s:7,e:9,label:"Monitoring",type:"maint"},{s:9,e:12,label:"Extension",type:"build"}] },
      { id:10, name: "FS Forecasting",        phases: [{s:0,e:1,label:"A&D",type:"ad"},{s:1,e:5,label:"Build",type:"build"},{s:5,e:6,label:"Bench",type:"bench"},{s:6,e:7,label:"Handover",type:"handover"},{s:7,e:9,label:"Improvements",type:"maint"},{s:9,e:12,label:"TabH2O Ext",type:"build"}] },
      { id:11, name: "Txn Intelligence",      phases: [{s:0,e:1,label:"A&D",type:"ad"},{s:1,e:8,label:"Build",type:"build"},{s:8,e:10,label:"Bench",type:"bench"},{s:10,e:12,label:"Handover",type:"handover"}] },
      { id:12, name: "Fraud Detection",       phases: [{s:0,e:1,label:"A&D",type:"ad"},{s:1,e:5,label:"Build",type:"build"},{s:5,e:6,label:"Bench",type:"bench"},{s:6,e:7,label:"Handover",type:"handover"},{s:7,e:9,label:"Maint",type:"maint"}] },
    ]
  },

  // ── STAKEHOLDERS ───────────────────────────────────────────────────────
  stakeholders: {
    h2o: [
      { name: "Yohan Trevoy",   role: "VP of Engineering",          type: "h2o", focus: "Delivery Lead / Account Owner" },
      { name: "Shivam Bansal",  role: "Kaggle Grandmaster / Lead",   type: "h2o", focus: "Primary Engagement Lead" },
      { name: "Mark Landry",    role: "Kaggle Grandmaster",          type: "h2o", focus: "IB&M Hedging Advisory" },
      { name: "Eu Jin Lok",     role: "Kaggle Grandmaster",          type: "h2o", focus: "SLM Factory / IB&M" },
      { name: "Pascal Peiffer", role: "Kaggle Grandmaster",          type: "h2o", focus: "SLM Factory Advisory" },
      { name: "Loveneet",       role: "AI Partnerships",             type: "h2o", focus: "Commercial / Partnership" },
      { name: "Ishan",          role: "AI Scientist / FDE",          type: "h2o", focus: "BB Predictive / MLOps" },
      { name: "Phil",           role: "Tech Lead FDE",               type: "h2o", focus: "FS Forecasting / Txn Intelligence" },
      { name: "Tristan",        role: "FDE AI Scientist",            type: "h2o", focus: "Txn Intelligence / FS" },
      { name: "Sean",           role: "FDE AI Engineer",             type: "h2o", focus: "Txn Intelligence / Fraud" },
      { name: "Rohit",          role: "FDE Data Scientist",          type: "h2o", focus: "BB Predictive / Home Buying" },
      { name: "Piraveen",       role: "FDE AI Engineer",             type: "h2o", focus: "SLM Factory / IB&M" },
      { name: "Sunny",          role: "FDE AI Scientist",            type: "h2o", focus: "SLM Factory / BB SLMs" },
    ],
    cba: [
      { name: "Dan Jermyn",      role: "Chief Decision Scientist",   type: "cba", focus: "Executive Sponsor" },
      { name: "David Rowe",      role: "Head of AI Platform (CDAO)", type: "cba", focus: "SLM Factory / Txn Intelligence" },
      { name: "Tyrone Pollard",  role: "CDAO AI Platform",           type: "cba", focus: "SLM Factory / Txn Intelligence" },
      { name: "Ranil",           role: "Governance",                 type: "cba", focus: "Governance Committee" },
      { name: "Chris Austin",    role: "Governance",                 type: "cba", focus: "Governance Committee" },
      { name: "Pablo",           role: "Finance",                    type: "cba", focus: "Financial Approvals" },
      { name: "Zoe",             role: "Supplier Risk",              type: "cba", focus: "Pricing Calls" },
      { name: "Sandhya",         role: "Procurement",                type: "cba", focus: "Procurement / SOW" },
      { name: "Boris Kogan",     role: "RBS AI Lead",                type: "cba", focus: "RBS SLMs" },
      { name: "Sonal Surana",    role: "BB AI Lead",                 type: "cba", focus: "BB SLMs" },
      { name: "Abdul Karim",     role: "BB AI Engineer",             type: "cba", focus: "BB SLMs" },
      { name: "Andrea Schmidt",  role: "IB&M",                      type: "cba", focus: "IB&M Hedging" },
      { name: "Oliver Fleming",  role: "Financial Services",         type: "cba", focus: "FS Forecasting" },
    ]
  },

  // ── COMMERCIAL USAGE MODEL (from NEW - Usage sheet) ────────────────────
  usageModel: [
    { ucId: 1,  buildCost: 5000000, maintenancePct: 0.20, usageQtr: 500000,  totalY1: 500000,  totalY2: 3000000 },
    { ucId: 7,  buildCost: 3000000, maintenancePct: 0.20, usageQtr: 300000,  totalY1: 600000,  totalY2: 1800000 },
    { ucId: 2,  buildCost: 2000000, maintenancePct: 0.20, usageQtr: 200000,  totalY1: 400000,  totalY2: 1200000 },
  ],

  // ── RESOURCING ─────────────────────────────────────────────────────────
  teamRoles: [
    { role: "Delivery Lead / KGM",    count: 2,  tbd: 0,  cost_usd_m: 1.5 },
    { role: "Tech Lead FDE",           count: 3,  tbd: 2,  cost_usd_m: null },
    { role: "FDE AI Engineer",         count: 4,  tbd: 6,  cost_usd_m: null },
    { role: "FDE AI Scientist",        count: 3,  tbd: 4,  cost_usd_m: null },
    { role: "KGM Advisory",            count: 3,  tbd: 0,  cost_usd_m: null },
    { role: "Product Engineering",     count: 3,  tbd: 0,  cost_usd_m: null },
    { role: "DevOps",                  count: 0,  tbd: 2,  cost_usd_m: null },
  ],

  // ── RECRUITMENT TRACKER ────────────────────────────────────────────────
  // Source: Resourcing V1 — columns F (Delivery Lead), G (Tech Lead),
  //         H (FDE AI Engineer), I (FDE AI Scientist) — all TBH entries
  //         plus DevOps and Full Stack from the 15-Hirings summary box.
  recruitment: {
    summary: { total: 15, delivery_leads: 2, tech_leads: 2, ai_engineers: 4, data_scientists: 2, devops: 2, full_stack: 3 },
    roles: [
      // ── Delivery Leads ────────────────────────────────────────────────
      { id: "DL-1",  tbhRef: "Delivery Lead 1", title: "Delivery Lead",     type: "delivery_lead",  roleCol: "Delivery Lead (F)", location: "Sydney",             ucId: 1,  ucName: "SLM Factory — Core Capability Build",       priority: "critical", status: "open" },
      { id: "DL-2",  tbhRef: "Delivery Lead 2", title: "Delivery Lead",     type: "delivery_lead",  roleCol: "Delivery Lead (F)", location: "Sydney",             ucId: 8,  ucName: "BB Predictive Models Uplift",                priority: "critical", status: "open" },
      // ── Tech Leads ───────────────────────────────────────────────────
      { id: "TL-1",  tbhRef: "TBH-1 (Syd)",    title: "Tech Lead FDE",     type: "tech_lead",      roleCol: "Tech Lead (G)",     location: "Sydney",             ucId: 3,  ucName: "BB SLM — Document Classification",           priority: "high",     status: "open" },
      { id: "TL-2",  thhRef: "TBH-1 (Syd)",    title: "Tech Lead FDE",     type: "tech_lead",      roleCol: "Tech Lead (G)",     location: "Sydney",             ucId: 13, ucName: "MLOps Revamp",                               priority: "high",     status: "open" },
      // ── AI Engineers (FDE) ───────────────────────────────────────────
      { id: "ENG-1", tbbRef: "TBH-2 (Syd)",    title: "FDE AI Engineer",   type: "ai_engineer",    roleCol: "AI Engineer (H)",   location: "Sydney",             ucId: 3,  ucName: "BB SLM — Document Classification",           priority: "high",     status: "open" },
      { id: "ENG-2", tbbRef: "TBH-3 (Syd)",    title: "FDE AI Engineer",   type: "ai_engineer",    roleCol: "AI Engineer (H)",   location: "Sydney",             ucId: 3,  ucName: "BB SLM — Document Classification",           priority: "high",     status: "open" },
      { id: "ENG-3", tbbRef: "TBH-7 (Syd)",    title: "FDE AI Engineer",   type: "ai_engineer",    roleCol: "AI Engineer (H)",   location: "Sydney",             ucId: 12, ucName: "COO Fraud Detection — UC1 (Auto Model Train)", priority: "medium",   status: "open" },
      { id: "ENG-4", tbbRef: "TBH-8 (Syd)",    title: "FDE AI Engineer",   type: "ai_engineer",    roleCol: "AI Engineer (H)",   location: "Sydney",             ucId: 12, ucName: "COO Fraud Detection — UC3 (Infra Efficiency)", priority: "medium",   status: "open" },
      // ── Data Scientists (FDE) ────────────────────────────────────────
      { id: "DS-1",  tbbRef: "TBH-4 (Syd)",    title: "FDE Data Scientist", type: "data_scientist", roleCol: "AI Scientist (I)",  location: "Sydney",             ucId: 1,  ucName: "SLM Factory — Core Capability Build",       priority: "critical", status: "open" },
      { id: "DS-2",  tbbRef: "TBH-5 (Syd)",    title: "FDE Data Scientist", type: "data_scientist", roleCol: "AI Scientist (I)",  location: "Sydney",             ucId: 7,  ucName: "IB&M Predictive Hedging Foundation Model",  priority: "high",     status: "open" },
      // ── DevOps ───────────────────────────────────────────────────────
      { id: "DEV-1", tbbRef: "TBH-11 (DevOps)", title: "DevOps Engineer",   type: "devops",         roleCol: "Specialist",        location: "Sydney",             ucId: null, ucName: "Platform / General Infra",                priority: "high",     status: "open" },
      { id: "DEV-2", tbbRef: "TBH-12 (DevOps)", title: "DevOps Engineer",   type: "devops",         roleCol: "Specialist",        location: "Sydney",             ucId: 13, ucName: "MLOps Revamp + General Infra",               priority: "high",     status: "open" },
      // ── Full Stack Engineers (Product / KGM team) ────────────────────
      { id: "FSE-1", tbbRef: "Full Stack 1",    title: "Full Stack Engineer", type: "full_stack",   roleCol: "Product Eng",       location: "Sydney / Offshore",  ucId: 1,  ucName: "SLM Factory — Product Engineering Support", priority: "medium",   status: "open" },
      { id: "FSE-2", tbbRef: "Full Stack 2",    title: "Full Stack Engineer", type: "full_stack",   roleCol: "Product Eng",       location: "Sydney / Offshore",  ucId: 1,  ucName: "SLM Factory — Product Engineering Support", priority: "medium",   status: "open" },
      { id: "FSE-3", tbbRef: "Full Stack 3",    title: "Full Stack Engineer", type: "full_stack",   roleCol: "Product Eng",       location: "Sydney / Offshore",  ucId: 7,  ucName: "IB&M — Product Engineering Support",        priority: "medium",   status: "open" },
    ],
  },

  // ── OPEN ACTION ITEMS ─────────────────────────────────────────────────
  actions: [
    { id:1,  area:"Commercial", priority:"high",   item:"Cost breakdown per use case — distinguish license, customisation, PS, platform, maintenance" },
    { id:2,  area:"Commercial", priority:"high",   item:"Delivery & payment roadmap — milestone-based, staggered across use cases" },
    { id:3,  area:"Commercial", priority:"high",   item:"COGS / Hiring Plan — engineering resourcing requirements for delivery" },
    { id:4,  area:"Commercial", priority:"medium", item:"Confirm GST — is current pricing inclusive or exclusive?" },
    { id:5,  area:"Commercial", priority:"medium", item:"Reconcile $7.9M platform commitment with new SOW proposals" },
    { id:6,  area:"Commercial", priority:"high",   item:"Close commitment gap — strategy to move from $25M mapped to $100M total" },
    { id:7,  area:"Technical",  priority:"medium", item:"MLOps Revamp scoping — confirm integration approach before next SOW revision" },
    { id:8,  area:"Technical",  priority:"high",   item:"Transaction Intelligence schema finalisation — lock schema and signal priorities at M1" },
    { id:9,  area:"Technical",  priority:"high",   item:"IB&M Foundation Model execution — begin TabH2O-F build (Q3 2026)" },
    { id:10, area:"Technical",  priority:"high",   item:"SLM Factory build kickoff — initiate Labelling Factory + Distillation Engine" },
    { id:11, area:"Governance", priority:"medium", item:"Tier 0 Status uplift — complete formal documentation" },
    { id:12, area:"Governance", priority:"high",   item:"SOW execution kickoff — formal programme start across all confirmed use cases" },
  ],
};

// ── COMPUTED HELPERS ─────────────────────────────────────────────────────

CBA_DATA.computed = {
  get totalTCV() {
    return CBA_DATA.usecases.reduce((s, u) => s + u.tcv, 0);
  },
  get activeTCV() {
    return CBA_DATA.usecases.filter(u => u.status === 'green').reduce((s, u) => s + u.tcv, 0);
  },
  get greenCount() {
    return CBA_DATA.usecases.filter(u => u.status === 'green').length;
  },
  get amberCount() {
    return CBA_DATA.usecases.filter(u => u.status === 'amber').length;
  },
  get redCount() {
    return CBA_DATA.usecases.filter(u => u.status === 'red').length;
  },
  get commitmentGap() {
    return CBA_DATA.partnership.commitment - CBA_DATA.computed.activeTCV;
  },
  get tcvByBU() {
    const map = {};
    CBA_DATA.usecases.forEach(u => {
      if (!map[u.bu]) map[u.bu] = 0;
      map[u.bu] += u.tcv;
    });
    return map;
  },
  get tcvByCategory() {
    const map = {};
    CBA_DATA.usecases.forEach(u => {
      if (!map[u.category]) map[u.category] = 0;
      map[u.category] += u.tcv;
    });
    return map;
  },
  ucById(id) {
    return CBA_DATA.usecases.find(u => u.id === id);
  },
};

// Freeze to prevent accidental mutations
Object.freeze(CBA_DATA.partnership);
